{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright © Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-django is now available for Red Hat OpenStack Platform\n18.0.3 (Feature Release 1) (Antelope).\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Django is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\n\nSecurity Fix(es):\n\n* Potential denial-of-service in django.utils.html.urlize()\n(CVE-2024-38875)\n\n* Potential denial-of-service in\ndjango.utils.translation.get_supported_language_variant() (CVE-2024-39614)\n\n* Username enumeration through timing difference for users with unusable\npasswords (CVE-2024-39329)\n\n* Potential directory-traversal in django.core.files.storage.Storage.save()\n(CVE-2024-39330)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat products and services.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2024:9481",
				"url": "https://access.redhat.com/errata/RHSA-2024:9481"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "2295935",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295935"
			},
			{
				"category": "external",
				"summary": "2295936",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295936"
			},
			{
				"category": "external",
				"summary": "2295937",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295937"
			},
			{
				"category": "external",
				"summary": "2295938",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295938"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_9481.json"
			}
		],
		"title": "Red Hat Security Advisory: Red Hat OpenStack Platform 18.0.3 (python-django) security update",
		"tracking": {
			"current_release_date": "2025-02-12T06:11:43+00:00",
			"generator": {
				"date": "2025-02-12T06:11:43+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "4.3.0"
				}
			},
			"id": "RHSA-2024:9481",
			"initial_release_date": "2024-11-13T13:16:47+00:00",
			"revision_history": [
				{
					"date": "2024-11-13T13:16:47+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2024-11-13T13:16:47+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2025-02-12T06:11:43+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat OpenStack Services on OpenShift 18.0",
								"product": {
									"name": "Red Hat OpenStack Services on OpenShift 18.0",
									"product_id": "9Base-RHOSO-18.0",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:18.0::el9"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Services on OpenShift"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django-0:3.2.12-8.el9ost.src",
								"product": {
									"name": "python-django-0:3.2.12-8.el9ost.src",
									"product_id": "python-django-0:3.2.12-8.el9ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-django@3.2.12-8.el9ost?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-django-0:3.2.12-8.el9ost.noarch",
								"product": {
									"name": "python3-django-0:3.2.12-8.el9ost.noarch",
									"product_id": "python3-django-0:3.2.12-8.el9ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-django@3.2.12-8.el9ost?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-0:3.2.12-8.el9ost.src as a component of Red Hat OpenStack Services on OpenShift 18.0",
					"product_id": "9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src"
				},
				"product_reference": "python-django-0:3.2.12-8.el9ost.src",
				"relates_to_product_reference": "9Base-RHOSO-18.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-django-0:3.2.12-8.el9ost.noarch as a component of Red Hat OpenStack Services on OpenShift 18.0",
					"product_id": "9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
				},
				"product_reference": "python3-django-0:3.2.12-8.el9ost.noarch",
				"relates_to_product_reference": "9Base-RHOSO-18.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-38875",
			"cwe": {
				"id": "CWE-1287",
				"name": "Improper Validation of Specified Type of Input"
			},
			"discovery_date": "2024-07-05T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2295935"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A vulnerability was found in the Django framework's urlize and urlizetrunc functions, where an attacker can input a certain string containing a large number of brackets, leads to a potential denial of service when the application attempts to process the excessive input.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: Potential denial-of-service in django.utils.html.urlize()",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
					"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-38875"
				},
				{
					"category": "external",
					"summary": "RHBZ#2295935",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295935"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-38875",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-38875"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-38875",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-38875"
				}
			],
			"release_date": "2024-07-26T06:26:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"date": "2024-11-13T13:16:47+00:00",
					"details": "Before applying this update, make sure all previously released errata relevant to your system have been applied.\n\nFor details on how to apply this update as a new RHOSO 18.0 deployment, see\n“Deploying Red Hat OpenStack Services on OpenShift” at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/index\n\nFor details on how to apply this update to an existing RHOSO 18.0 deployment, see \"Updating your environment to the latest maintenance release\" at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/updating_your_environment_to_the_latest_maintenance_release/index",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:9481"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "LOW",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-django: Potential denial-of-service in django.utils.html.urlize()"
		},
		{
			"cve": "CVE-2024-39329",
			"cwe": {
				"id": "CWE-208",
				"name": "Observable Timing Discrepancy"
			},
			"discovery_date": "2024-07-05T09:46:29+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2295936"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A vulnerability was found in Python-Django in the django.contrib.auth.backends.ModelBackend.authenticate() method. This flaw allows remote attackers to enumerate users via a timing attack involving login requests for users with unusable passwords.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: Username enumeration through timing difference for users with unusable passwords",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
					"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-39329"
				},
				{
					"category": "external",
					"summary": "RHBZ#2295936",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295936"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-39329",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-39329"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-39329",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39329"
				}
			],
			"release_date": "2024-07-09T14:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"date": "2024-11-13T13:16:47+00:00",
					"details": "Before applying this update, make sure all previously released errata relevant to your system have been applied.\n\nFor details on how to apply this update as a new RHOSO 18.0 deployment, see\n“Deploying Red Hat OpenStack Services on OpenShift” at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/index\n\nFor details on how to apply this update to an existing RHOSO 18.0 deployment, see \"Updating your environment to the latest maintenance release\" at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/updating_your_environment_to_the_latest_maintenance_release/index",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:9481"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "HIGH",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 3.7,
						"baseSeverity": "LOW",
						"confidentialityImpact": "LOW",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Low"
				}
			],
			"title": "python-django: Username enumeration through timing difference for users with unusable passwords"
		},
		{
			"cve": "CVE-2024-39330",
			"cwe": {
				"id": "CWE-22",
				"name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
			},
			"discovery_date": "2024-07-05T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2295937"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A vulnerability was found in Python-Django in the Derived classes of the django.core.files.storage.Storage base class that overrides the generate_filename() without replicating the file path validations existing in the parent class. This flaw allows potential directory traversal via certain inputs when calling save(). Built-in Storage sub-classes were not affected by this vulnerability.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: Potential directory-traversal in django.core.files.storage.Storage.save()",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
					"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-39330"
				},
				{
					"category": "external",
					"summary": "RHBZ#2295937",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295937"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-39330",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-39330"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-39330",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39330"
				}
			],
			"release_date": "2024-07-09T14:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"date": "2024-11-13T13:16:47+00:00",
					"details": "Before applying this update, make sure all previously released errata relevant to your system have been applied.\n\nFor details on how to apply this update as a new RHOSO 18.0 deployment, see\n“Deploying Red Hat OpenStack Services on OpenShift” at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/index\n\nFor details on how to apply this update to an existing RHOSO 18.0 deployment, see \"Updating your environment to the latest maintenance release\" at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/updating_your_environment_to_the_latest_maintenance_release/index",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:9481"
				},
				{
					"category": "workaround",
					"details": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 4.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "LOW",
						"integrityImpact": "NONE",
						"privilegesRequired": "LOW",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Low"
				}
			],
			"title": "python-django: Potential directory-traversal in django.core.files.storage.Storage.save()"
		},
		{
			"cve": "CVE-2024-39614",
			"cwe": {
				"id": "CWE-1287",
				"name": "Improper Validation of Specified Type of Input"
			},
			"discovery_date": "2024-07-05T09:46:30+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2295938"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A vulnerability was found in Python-Django in the get_supported_language_variant() function. The issue triggers when parsed with very long strings, including a specific set of characters, leading to a potential denial of service attack.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "python-django: Potential denial-of-service in django.utils.translation.get_supported_language_variant()",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
					"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2024-39614"
				},
				{
					"category": "external",
					"summary": "RHBZ#2295938",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2295938"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2024-39614",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-39614"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2024-39614",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39614"
				}
			],
			"release_date": "2024-07-09T14:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"date": "2024-11-13T13:16:47+00:00",
					"details": "Before applying this update, make sure all previously released errata relevant to your system have been applied.\n\nFor details on how to apply this update as a new RHOSO 18.0 deployment, see\n“Deploying Red Hat OpenStack Services on OpenShift” at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/index\n\nFor details on how to apply this update to an existing RHOSO 18.0 deployment, see \"Updating your environment to the latest maintenance release\" at\nhttps://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/updating_your_environment_to_the_latest_maintenance_release/index",
					"product_ids": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2024:9481"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "LOW",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"9Base-RHOSO-18.0:python-django-0:3.2.12-8.el9ost.src",
						"9Base-RHOSO-18.0:python3-django-0:3.2.12-8.el9ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "python-django: Potential denial-of-service in django.utils.translation.get_supported_language_variant()"
		}
	]
}
