{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-django is now available for Red Hat OpenStack Platform\n15 (Stein).\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Django is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\n\nSecurity Fix(es):\n\n* Incorrect HTTP detection with reverse-proxy connecting via HTTPS\n(CVE-2019-12781)\n\n* backtracking in a regular expression in django.utils.text.Truncator leads\nto DoS (CVE-2019-14232)\n\n* the behavior of the underlying HTMLParser leading to DoS (CVE-2019-14233)\n\n* SQL injection possibility in key and index lookups for\nJSONField/HStoreField (CVE-2019-14234)\n\n* Potential memory exhaustion in django.utils.encoding.uri_to_iri()\n(CVE-2019-14235)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2020:1324",
				"url": "https://access.redhat.com/errata/RHSA-2020:1324"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "external",
				"summary": "1724497",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1724497"
			},
			{
				"category": "external",
				"summary": "1734405",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734405"
			},
			{
				"category": "external",
				"summary": "1734410",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734410"
			},
			{
				"category": "external",
				"summary": "1734417",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734417"
			},
			{
				"category": "external",
				"summary": "1734422",
				"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734422"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2020/rhsa-2020_1324.json"
			}
		],
		"title": "Red Hat Security Advisory: python-django security update",
		"tracking": {
			"current_release_date": "2024-08-14T03:10:00+00:00",
			"generator": {
				"date": "2024-08-14T03:10:00+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.32.0"
				}
			},
			"id": "RHSA-2020:1324",
			"initial_release_date": "2020-04-06T09:02:39+00:00",
			"revision_history": [
				{
					"date": "2020-04-06T09:02:39+00:00",
					"number": "1",
					"summary": "Initial version"
				},
				{
					"date": "2020-04-06T09:02:39+00:00",
					"number": "2",
					"summary": "Last updated version"
				},
				{
					"date": "2024-08-14T03:10:00+00:00",
					"number": "3",
					"summary": "Last generated version"
				}
			],
			"status": "final",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat OpenStack Platform 15.0",
								"product": {
									"name": "Red Hat OpenStack Platform 15.0",
									"product_id": "8Base-RHOS-15.0",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:15::el8"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django-0:2.1.11-1.el8ost.src",
								"product": {
									"name": "python-django-0:2.1.11-1.el8ost.src",
									"product_id": "python-django-0:2.1.11-1.el8ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-django@2.1.11-1.el8ost?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
								"product": {
									"name": "python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
									"product_id": "python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-django-bash-completion@2.1.11-1.el8ost?arch=noarch"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-django-0:2.1.11-1.el8ost.noarch",
								"product": {
									"name": "python3-django-0:2.1.11-1.el8ost.noarch",
									"product_id": "python3-django-0:2.1.11-1.el8ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-django@2.1.11-1.el8ost?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-0:2.1.11-1.el8ost.src as a component of Red Hat OpenStack Platform 15.0",
					"product_id": "8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src"
				},
				"product_reference": "python-django-0:2.1.11-1.el8ost.src",
				"relates_to_product_reference": "8Base-RHOS-15.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-bash-completion-0:2.1.11-1.el8ost.noarch as a component of Red Hat OpenStack Platform 15.0",
					"product_id": "8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch"
				},
				"product_reference": "python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
				"relates_to_product_reference": "8Base-RHOS-15.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-django-0:2.1.11-1.el8ost.noarch as a component of Red Hat OpenStack Platform 15.0",
					"product_id": "8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				},
				"product_reference": "python3-django-0:2.1.11-1.el8ost.noarch",
				"relates_to_product_reference": "8Base-RHOS-15.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"acknowledgments": [
				{
					"names": [
						"the Django project"
					]
				},
				{
					"names": [
						"Gavin Wahl"
					],
					"summary": "Acknowledged by upstream."
				}
			],
			"cve": "CVE-2019-12781",
			"cwe": {
				"id": "CWE-444",
				"name": "Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')"
			},
			"discovery_date": "2019-06-24T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1724497"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An HTTP detection flaw was discovered in Django.  If deployed behind a reverse-proxy connecting to Django via HTTPS,  django.http.HttpRequest.scheme() incorrectly detected client requests made using HTTP as using HTTPS.  This resulted in incorrect results for is_secure() and build_absolute_uri(), and HTTP requests were not correctly redirected to HTTPS in accordance with SECURE_SSL_REDIRECT.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue does not affect any versions of python-django as shipped with Red Hat Update Infrastructure for Cloud Providers as the load balancer should not be configured to forward HTTP requests.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
					"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
					"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-12781"
				},
				{
					"category": "external",
					"summary": "RHBZ#1724497",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1724497"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-12781",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-12781"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-12781",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-12781"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/"
				}
			],
			"release_date": "2019-07-01T00:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2020:1324"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "HIGH",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 4.8,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "LOW",
						"integrityImpact": "LOW",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS"
		},
		{
			"acknowledgments": [
				{
					"names": [
						"the Django project"
					]
				}
			],
			"cve": "CVE-2019-14232",
			"cwe": {
				"id": "CWE-20",
				"name": "Improper Input Validation"
			},
			"discovery_date": "2019-07-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1734405"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python-django as shipped with Red Hat Gluster Storage 3, Red Hat Ceph Storage 2 and 3, as it contains the vulnerable code.\n\nThis issue affects Red Hat Update Infrastructure for Cloud Providers, but the vulnerable functions in python-django are currently not used in any part of the Product.\n\nThis issue does not affect Red Hat Satellite as the vulnerable functions in python-django are not used.\n\nRed Hat OpenStack Platform:                                                                                                                 \n* This issue affects all versions of python-django shipped with Red Hat Openstack Platform versions 9-15, as it contains the vulnerable code.\n* Because the flaw's impact is Medium, it will not be fixed in Red Hat Openstack Platform 9 which is retiring on 8/24.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
					"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
					"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-14232"
				},
				{
					"category": "external",
					"summary": "RHBZ#1734405",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734405"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-14232",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-14232"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-14232",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14232"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
				}
			],
			"release_date": "2019-08-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2020:1324"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "LOW",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS"
		},
		{
			"acknowledgments": [
				{
					"names": [
						"the Django project"
					]
				}
			],
			"cve": "CVE-2019-14233",
			"cwe": {
				"id": "CWE-20",
				"name": "Improper Input Validation"
			},
			"discovery_date": "2019-07-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1734410"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: the behavior of the underlying HTMLParser leading to DoS",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python-django as shipped with Red Hat Gluster Storage 3, Red Hat Ceph Storage 2 and 3, as it contains the vulnerable code.\n\nThis issue affects Red Hat Update Infrastructure for Cloud Providers, but the vulnerable functions in python-django are currently not used in any part of the Product.\n\nThis issue does not affect Red Hat Satellite as the vulnerable functions in python-django are not used.\n\nRed Hat OpenStack Platform:                                                                                                                 \n* This issue affects all versions of python-django shipped with Red Hat Openstack Platform versions 9-15, as it contains the vulnerable code.\n* Because the flaw's impact is Medium, it will not be fixed in Red Hat Openstack Platform 9 which is retiring on 8/24.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
					"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
					"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-14233"
				},
				{
					"category": "external",
					"summary": "RHBZ#1734410",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734410"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-14233",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-14233"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-14233",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14233"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
				}
			],
			"release_date": "2019-08-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2020:1324"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "LOW",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: the behavior of the underlying HTMLParser leading to DoS"
		},
		{
			"acknowledgments": [
				{
					"names": [
						"the Django project"
					]
				}
			],
			"cve": "CVE-2019-14234",
			"cwe": {
				"id": "CWE-20",
				"name": "Improper Input Validation"
			},
			"discovery_date": "2019-07-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1734417"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: SQL injection possibility in key and index lookups for JSONField/HStoreField",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python-django as shipped with Red Hat Gluster Storage 3, Red Hat Ceph Storage 2 and 3, as it contains the vulnerable code.\n\nThis issue affects Red Hat Update Infrastructure for Cloud Providers, but the vulnerable functions in python-django are currently not used in any part of the Product.\n\nThis issue does not affect Red Hat Satellite as the vulnerable functions in python-django are not used.\n\nRed Hat OpenStack Platform:\n* This issue affects all versions of python-django shipped with Red Hat Openstack Platform versions 9-15, as it contains the vulnerable code. However, the version of python-django shipped with Red Hat Openstack Platform versions 9 & 10 do not contain the code for JSONFields. \n* Because the flaw's impact is Medium, it will not be fixed in Red Hat Openstack Platform 9 which is retiring on 8/24.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
					"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
					"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-14234"
				},
				{
					"category": "external",
					"summary": "RHBZ#1734417",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734417"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-14234",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-14234"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-14234",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14234"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
				}
			],
			"release_date": "2019-08-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2020:1324"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "LOW",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: SQL injection possibility in key and index lookups for JSONField/HStoreField"
		},
		{
			"acknowledgments": [
				{
					"names": [
						"the Django project"
					]
				}
			],
			"cve": "CVE-2019-14235",
			"cwe": {
				"id": "CWE-400",
				"name": "Uncontrolled Resource Consumption"
			},
			"discovery_date": "2019-07-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "1734422"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()",
					"title": "Vulnerability summary"
				},
				{
					"category": "other",
					"text": "This issue affects the versions of python-django as shipped with Red Hat Gluster Storage 3, Red Hat Ceph Storage 2 and 3, as it contains the vulnerable code.\n\nThis issue affects Red Hat Update Infrastructure for Cloud Providers, but the vulnerable functions in python-django are currently not used in any part of the Product.\n\nThis issue does not affect Red Hat Satellite as the vulnerable functions in python-django are not used.\n\nRed Hat OpenStack Platform:                                                                                                                 \n* This issue affects all versions of python-django shipped with Red Hat Openstack Platform versions 9-15, as it contains the vulnerable code.\n* Because the flaw's impact is Medium, it will not be fixed in Red Hat Openstack Platform 9 which is retiring 8/24.",
					"title": "Statement"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
					"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
					"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2019-14235"
				},
				{
					"category": "external",
					"summary": "RHBZ#1734422",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1734422"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2019-14235",
					"url": "https://www.cve.org/CVERecord?id=CVE-2019-14235"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2019-14235",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14235"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
				}
			],
			"release_date": "2019-08-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2020:1324"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "LOW",
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"8Base-RHOS-15.0:python-django-0:2.1.11-1.el8ost.src",
						"8Base-RHOS-15.0:python-django-bash-completion-0:2.1.11-1.el8ost.noarch",
						"8Base-RHOS-15.0:python3-django-0:2.1.11-1.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()"
		}
	]
}
