{
	"document": {
		"aggregate_severity": {
			"namespace": "https://access.redhat.com/security/updates/classification/",
			"text": "Moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright Â© Red Hat, Inc. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "An update for python-django20 is now available for Red Hat OpenStack\nPlatform 16.2.4 (Train) for Red Hat Enterprise Linux (RHEL) 8.4.\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.",
				"title": "Topic"
			},
			{
				"category": "general",
				"text": "Security Fix(es):\n\n* Possible XSS via '{% debug %}' template tag (CVE-2022-22818)\n\n* Denial of service possibility in file uploads (CVE-2022-23833)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.",
				"title": "Details"
			},
			{
				"category": "legal_disclaimer",
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://access.redhat.com/security/team/contact/",
			"issuing_authority": "Red Hat Product Security is responsible for vulnerability handling across all Red Hat offerings.",
			"name": "Red Hat Product Security",
			"namespace": "https://www.redhat.com"
		},
		"references": [
			{
				"category": "self",
				"summary": "https://access.redhat.com/errata/RHSA-2022:8853",
				"url": "https://access.redhat.com/errata/RHSA-2022:8853"
			},
			{
				"category": "external",
				"summary": "https://access.redhat.com/security/updates/classification/#moderate",
				"url": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"category": "self",
				"summary": "Canonical URL",
				"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2022/rhsa-2022_8853.json"
			}
		],
		"title": "Red Hat Security Advisory: Red Hat OpenStack Platform 16.2.4 (python-django20) security update",
		"tracking": {
			"current_release_date": "2022-12-07T19:19:49+00:00",
			"generator": {
				"date": "2023-10-17T17:20:08+00:00",
				"engine": {
					"name": "Red Hat SDEngine",
					"version": "3.23.0"
				}
			},
			"id": "RHSA-2022:8853",
			"initial_release_date": "2022-12-07T19:19:49+00:00",
			"revision_history": [
				{
					"date": "2022-12-07T19:19:49+00:00",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "Red Hat OpenStack Platform 16.2",
								"product": {
									"name": "Red Hat OpenStack Platform 16.2",
									"product_id": "8Base-RHOS-16.2",
									"product_identification_helper": {
										"cpe": "cpe:/a:redhat:openstack:16.2::el8"
									}
								}
							}
						],
						"category": "product_family",
						"name": "Red Hat OpenStack Platform"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django20-0:2.0.13-18.el8ost.src",
								"product": {
									"name": "python-django20-0:2.0.13-18.el8ost.src",
									"product_id": "python-django20-0:2.0.13-18.el8ost.src",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python-django20@2.0.13-18.el8ost?arch=src"
									}
								}
							}
						],
						"category": "architecture",
						"name": "src"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-django20-0:2.0.13-18.el8ost.noarch",
								"product": {
									"name": "python3-django20-0:2.0.13-18.el8ost.noarch",
									"product_id": "python3-django20-0:2.0.13-18.el8ost.noarch",
									"product_identification_helper": {
										"purl": "pkg:rpm/redhat/python3-django20@2.0.13-18.el8ost?arch=noarch"
									}
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					}
				],
				"category": "vendor",
				"name": "Red Hat"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django20-0:2.0.13-18.el8ost.src as a component of Red Hat OpenStack Platform 16.2",
					"product_id": "8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src"
				},
				"product_reference": "python-django20-0:2.0.13-18.el8ost.src",
				"relates_to_product_reference": "8Base-RHOS-16.2"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-django20-0:2.0.13-18.el8ost.noarch as a component of Red Hat OpenStack Platform 16.2",
					"product_id": "8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
				},
				"product_reference": "python3-django20-0:2.0.13-18.el8ost.noarch",
				"relates_to_product_reference": "8Base-RHOS-16.2"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2022-22818",
			"cwe": {
				"id": "CWE-79",
				"name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
			},
			"discovery_date": "2022-01-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2048775"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in Django. The ``{% debug %}`` template tag did not properly encode the current context, posing a Cross-site scripting attack vector (XSS).",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Possible XSS via '{% debug %}' template tag",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
					"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2022-22818"
				},
				{
					"category": "external",
					"summary": "RHBZ#2048775",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2048775"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2022-22818",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-22818"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2022-22818",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-22818"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
				}
			],
			"release_date": "2022-02-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2022:8853"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"confidentialityImpact": "LOW",
						"integrityImpact": "LOW",
						"privilegesRequired": "NONE",
						"scope": "CHANGED",
						"userInteraction": "REQUIRED",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Possible XSS via '{% debug %}' template tag"
		},
		{
			"cve": "CVE-2022-23833",
			"cwe": {
				"id": "CWE-835",
				"name": "Loop with Unreachable Exit Condition ('Infinite Loop')"
			},
			"discovery_date": "2022-01-25T00:00:00+00:00",
			"ids": [
				{
					"system_name": "Red Hat Bugzilla ID",
					"text": "2048778"
				}
			],
			"notes": [
				{
					"category": "description",
					"text": "A flaw was found in Django. The issue occurs when passing certain inputs to multipart forms, resulting in an infinite loop when parsing files.",
					"title": "Vulnerability description"
				},
				{
					"category": "summary",
					"text": "Denial-of-service possibility in file uploads",
					"title": "Vulnerability summary"
				},
				{
					"category": "general",
					"text": "The CVSS score(s) listed for this vulnerability do not reflect the associated product's status, and are included for informational purposes to better understand the severity of this vulnerability.",
					"title": "CVSS score applicability"
				}
			],
			"product_status": {
				"fixed": [
					"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
					"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
				]
			},
			"references": [
				{
					"category": "self",
					"summary": "Canonical URL",
					"url": "https://access.redhat.com/security/cve/CVE-2022-23833"
				},
				{
					"category": "external",
					"summary": "RHBZ#2048778",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2048778"
				},
				{
					"category": "external",
					"summary": "https://www.cve.org/CVERecord?id=CVE-2022-23833",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-23833"
				},
				{
					"category": "external",
					"summary": "https://nvd.nist.gov/vuln/detail/CVE-2022-23833",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-23833"
				},
				{
					"category": "external",
					"summary": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
					"url": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
				}
			],
			"release_date": "2022-02-01T08:00:00+00:00",
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "For details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258",
					"product_ids": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
					],
					"restart_required": {
						"category": "none"
					},
					"url": "https://access.redhat.com/errata/RHSA-2022:8853"
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "HIGH",
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"privilegesRequired": "NONE",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"8Base-RHOS-16.2:python-django20-0:2.0.13-18.el8ost.src",
						"8Base-RHOS-16.2:python3-django20-0:2.0.13-18.el8ost.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"details": "Moderate"
				}
			],
			"title": "Denial-of-service possibility in file uploads"
		}
	]
}
